--DROP TABLE IF EXISTS family_members;
--DROP TABLE IF EXISTS payments;
--DROP TABLE IF EXISTS goods;
--DROP TABLE IF EXISTS good_types;

CREATE TABLE IF NOT EXISTS good_types (
    good_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    good_type_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS goods (
    good_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    good_name VARCHAR(100),
    type INT NOT NULL,
    FOREIGN KEY (type) REFERENCES good_types(good_type_id)
);

CREATE TABLE IF NOT EXISTS family_members (
    member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255) NOT NULL UNIQUE,
    member_name VARCHAR(250) NOT NULL,
    birthday TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_member INT NOT NULL,
    good INT NOT NULL,
    amount INT NOT NULL,
    unit_price INT NOT NULL,
    date DATE NOT NULL,
    FOREIGN KEY (family_member) REFERENCES family_members(member_id),
    FOREIGN KEY (good) REFERENCES goods(good_id)
);